sudo: false
language: python

python:
  - "2.7"
  - "3.4"

install:
    - pip install pep8 tox
    - pip3 install pep8 tox

before_script:
    - "pep8 --ignore=E402 ./bin ./zask ./tests"

script:
    - make test

branches:
  only:
    - master

notifications:
  slack:
    rooms:
      - juwai:BnihlKlSqagkR1FS7agVecXg
    on_success: never
    on_failure: always
